dependencies {
    // AnvilLib
    api(libs.anvillib)
    interfaceInjectionData(libs.anvillib.recipe)
    interfaceInjectionData(libs.anvillib.moveableEntityBlock)

    // Ageratum
    api(libs.ageratum)

    // AnvilCraft
    api(libs.anvilcraft)

    // JEI
    compileClasspath(libs.jei.common.api) { transitive = false }
    compileClasspath(libs.jei.neoforge.api) { transitive = false }
    compileClasspath(libs.jei.neoforge) { transitive = false }
    runtimeClasspath(libs.jei.neoforge) { transitive = false }

    // Jade
    compileClasspath(libs.jade)
    runtimeClasspath(libs.jade)
}
