# Jvm Info
java_version=21
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

# Mod Info
mod_id=anvilcraft_example_addon
mod_name=AnvilCraft: Example Addon
mod_description=An example AnvilCraft addon.
mod_author=Various Author
mod_license=LGPL-3.0-or-later
mod_version=1.0.0
mod_url=<unspecified>

# Development Info
maven_group=example.group

minecraft_version_range=[1.21,1.21.1)
neo_version_range=[21.0.0-beta,)
loader_version_range=[4,)

# Publish Info
modrinth_id=
curseforge_id=
