[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

anvillib = "2.0.0+snapshot.506"
ageratum = "0.0.1+build.111"
anvilcraft = "1.6.0+snapshot.2154"

jei = "19.32.0.358"
jade = "15.10.5+neoforge"

parchment = "2024.11.17"
mdg = "2.0.143"
lombok = "8.7.1"

[libraries]
anvillib-recipe = { group = "dev.anvilcraft.lib", name = "anvillib-recipe-neoforge-1.21.1", version.ref = "anvillib" }
anvillib-moveableEntityBlock = { group = "dev.anvilcraft.lib", name = "anvillib-moveable-entity-block-neoforge-1.21.1", version.ref = "anvillib" }
anvillib = { group = "dev.anvilcraft.lib", name = "anvillib-neoforge-1.21.1", version.ref = "anvillib" }
ageratum = { group = "dev.anvilcraft.resource", name = "ageratum-neoforge-1.21.1", version.ref = "ageratum" }
anvilcraft = { group = "dev.dubhe", name = "anvilcraft-neoforge-1.21.1", version.ref = "anvilcraft" }

jei-common-api = { group = "mezz.jei", name = "jei-1.21.1-common-api", version.ref = "jei" }
jei-neoforge-api = { group = "mezz.jei", name = "jei-1.21.1-neoforge-api", version.ref = "jei" }
jei-neoforge = { group = "mezz.jei", name = "jei-1.21.1-neoforge", version.ref = "jei" }
jade = { group = "maven.modrinth", name = "jade", version.ref = "jade" }

[plugins]
mdg = { id = "net.neoforged.moddev", version.ref = "mdg" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
